language: python
python:
- 2.7
- 3.6
script:
- python setup.py test
install:
- python setup.py build
deploy:
  provider: pypi
  user: bholten
  password:
    secure: LAftlgF6HeAL4Q/rvwSeE5RjCm0FDysBMGAGAeqdHK5J73TdmKZyn/z3iVv6DEyau4Y29U+2gjFffoGfUGxfzdr0TV1mfxDYMPR5SubdypdzmAY9PUqgz16pHCvLUNBrGtfvWwH4/T5r9WOlebfRkyWnM1uIemxglz/jJJRsG6eduuxzRrA5Ro9SRUv5WtHMldMLHmstz7TngCxJZqbsw+s4lsPTHWbG95Wh8TJDJcH1B5TT4eMp3WJO7Xo2JJbiWxbIH3VMqTNSI079PpZqXKmzxWWQUWOnte2+KMLgcdVSeePuRZmXS3nf9yDW566wTfyTiKtcs2zulxgRNYM7RmYnADkh9UN2RueZpQs7Bvx/xeRJnSsgxtTm++LdhczLY8Wgl0u5XkVcXyvqOX6IyKU99dlAZwqZzz2ZZgJguykBXsovPXMJQri1LLQy79qSFKKVVWmkCkWWfx4ncaunntek+J8raphBk29l7IsQ78ew96NXTB387wZxc/auHJ7SvkXP0EYek65yzV6uKxgj5o7tGQFHiIGkmgn2pVffcvxQ2a4WPmyL+IQ2y9dnSgwpik3w/eEux1WTu4BfF7Lst0db8beNBisWyN/FV4beerpwIaElp8NBxdv3I0NITPwNVC21PgkTP3SreTht9GffR3+bsIlwQLwEwzP7o19VCNc=
